set_property PACKAGE_PIN W5 [get_ports clk]
    set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN J3 [get_ports data]
    set_property IOSTANDARD LVCMOS33 [get_ports data]
    
set_property PACKAGE_PIN W7 [get_ports {LED_on[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED_on[6]}]
set_property PACKAGE_PIN W6 [get_ports {LED_on[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED_on[5]}]
set_property PACKAGE_PIN U8 [get_ports {LED_on[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED_on[4]}]
set_property PACKAGE_PIN V8 [get_ports {LED_on[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED_on[3]}]
set_property PACKAGE_PIN U5 [get_ports {LED_on[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED_on[2]}]
set_property PACKAGE_PIN V5 [get_ports {LED_on[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED_on[1]}]
set_property PACKAGE_PIN U7 [get_ports {LED_on[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED_on[0]}]
set_property PACKAGE_PIN U2 [get_ports {Activator[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Activator[0]}]
set_property PACKAGE_PIN U4 [get_ports {Activator[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Activator[1]}]
set_property PACKAGE_PIN V4 [get_ports {Activator[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Activator[2]}]
set_property PACKAGE_PIN W4 [get_ports {Activator[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Activator[3]}]

# Switches for sw_1
set_property PACKAGE_PIN V17 [get_ports {sw_1[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_1[0]}]
set_property PACKAGE_PIN V16 [get_ports {sw_1[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_1[1]}]
set_property PACKAGE_PIN W16 [get_ports {sw_1[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_1[2]}]
set_property PACKAGE_PIN W17 [get_ports {sw_1[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_1[3]}]
set_property PACKAGE_PIN W15 [get_ports {sw_1[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_1[4]}]
set_property PACKAGE_PIN V15 [get_ports {sw_1[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_1[5]}]
set_property PACKAGE_PIN W14 [get_ports {sw_1[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_1[6]}]
set_property PACKAGE_PIN W13 [get_ports {sw_1[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_1[7]}]
#Switches for option 
set_property PACKAGE_PIN T1 [get_ports {option[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {option[0]}]
set_property PACKAGE_PIN R2 [get_ports {option[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {option[1]}]
set_property PACKAGE_PIN U1 [get_ports {kurulum}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {kurulum}]
#Button
set_property PACKAGE_PIN U18 [get_ports {rst}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {rst}]
# LEDs
set_property PACKAGE_PIN U16 [get_ports {wind_warning}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {wind_warning}]
set_property PACKAGE_PIN E19 [get_ports {low_humid_warning}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {low_humid_warning}]
set_property PACKAGE_PIN U19 [get_ports {high_humid_warning}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {high_humid_warning}]
set_property PACKAGE_PIN V19 [get_ports {low_temp_warning}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {low_temp_warning}]
set_property PACKAGE_PIN W18 [get_ports {high_temp_warning}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {high_temp_warning}]
 
#HCSR
set_property PACKAGE_PIN J1 [get_ports echo1]
 set_property IOSTANDARD LVCMOS33 [get_ports echo1]
set_property PACKAGE_PIN L2 [get_ports trig]
 set_property IOSTANDARD LVCMOS33 [get_ports trig] 
#SOIL
set_property PACKAGE_PIN N2 [get_ports soil_humid]
 set_property IOSTANDARD LVCMOS33 [get_ports soil_humid]
set_property PACKAGE_PIN U15 [get_ports soil_warning]
 set_property IOSTANDARD LVCMOS33 [get_ports soil_warning] 